name: Deploy Flask app
 
on:
    workflow_dispatch:
        
jobs: 

    deploy:
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER}}
            DOCKER_TAG: ${{ github.sha}}

        runs-on: self-hosted
        
        steps:
             - name: Chekout code
               uses: actions/checkout@v4
            
             -  name: deploy wirh docker compose
                run:  docker compose pull && docker compose up -d --build --remove-orphans