---
#this is workflow name
name: Hello Workflow

# workflow runs whenever a code is pushed to main branch & now updated to run manually
# now workflow will run whenever ant html file on main branch is pushed or updated
on:
  #workflow_dispatch: null
  push:
   branches:
      - main
   paths: 
      - '**.html'
# this is the job declaration
jobs:

# this is job name which runs on ubuntu-latest(github privided ) -> every jobs need a runner either Github Runner or Self hosted runner (your own ec2 instance )
  greet:
    runs-on: ubuntu-latest
    # this is the step declaration -> steps needed to perform -> multiple steps can be run in one yml or workflow.
    steps:
      - name: say hello to user
        run: echo "Hello Navneet"
      - name: say hello to usernames
        run: echo "hello $USER"
  details:
      runs-on: ubuntu-latest
      steps:
        - name: version of python and docker
          run: docker --version && python --version
